### PR TITLE
Automatic dir creation

### PR DESCRIPTION
**Pull request by leonid-s-usov**
Got to the repository from original author's blog article comments. Had this contribution to share, hope you will find it useful

### CODE REVIEW

**Comment by ruleant** [comment]
Thanks for your contribution, I'll test it in the next few days.

**Comment by ruleant** [comment]
@leonid-s-usov 

I just tested with GIMP 2 on Windows 7 and your script fails when the folder doesn't exist (it works fine if the folder does exist). This is the message I get : 

```
Error while executing script-fu-save-android-icons:

Error: ( : 1) Procedure execution of python-fu-eval failed
```

I noticed your script requires Python, maybe some dependencies are not installed? If so, can you provide some documentation to install the required dependencies?
Or is there a way to create the folder without using python?

**Comment by leonid-s-usov** [comment]
you know, that's strange, since this line is executed always. So, if it was a dependency problem it would also fail in case the directory does exist. 
However here it seems that there is either a problem with the directory naming, or with the access rights during directory creation. We need to see what is the actual response from the python. 
I only have access to a Win 8 workstation, I will now try it there. Meanwhile, if you will, please try opening the python console and trying the code there (Filters->Python-Fu->Console)

```
import os
import errno
try:
    os.makedirs(os.path.dirname('C:\\temp\\dir\\to\\create\\file.png'))
except OSError as exception:
    if exception.errno != errno.EEXIST:
        raise
```

**Comment by leonid-s-usov** [comment]
I confirm the issue. The code runs fine in the python console directly, but fails when invoked via pdb.python_fu_eval('..'). os.mkdir or os.makedirs are for some reason causing it to fail.
The worst of all is that I can't find a way to make it print detailed description of the error. It just report "execution error" and that's all.
I will look into this

**Comment by leonid-s-usov** [comment]
That was tough...

**Comment by leonid-s-usov** [comment]
@ruleant 

> > Or is there a way to create the folder without using python?

I'm afraid there isn't. Tiny Scheme has no file utilities like that. Actually, other suggestions were about creating a separate python plugin that would do that, but that would make the installation harder. 
And then I have found out there was this eval function. You know the rest.

**Comment by gsiric** [comment]
Hi guys.
I just tested last commit, (WinXP and GIMP 2.8.14), seems to  work correctly.

**Comment by ruleant** [comment]
Good job @leonid-s-usov 
Tested it on Win7 64 bit with GIMP 2.8.14 and it works like a charm.

I'll test it on Linux later today

**Comment by ruleant** [comment]
Confirmed to work on Linux Kubuntu 14.04 with GIMP 2.8.10.

Thanks for submitting @leonid-s-usov

**Pull request merged**
